pull_request_rules:
  - name: automatic merge on approval and CI pass
    conditions:
     - "#approved-reviews-by>=1"
     - status-success=continuous-integration/AxaGuilDEv.react-toolkit/pr
     - label!=WIP
     - base=master
    actions:
      merge:
        method: merge